version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: Etc/Greenwich
  open-pull-requests-limit: 3
  allow:
  - dependency-name: rollbar
  - dependency-name: sidekiq
  - dependency-name: puma
  - dependency-name: foreman
  - dependency-name: byebug
  - dependency-name: dotenv
